  
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

  enable-experiment:
    - extension-methods

  exclude:
    - lib/**/**/*.freezed.dart
    - lib/**/**/*.g.dart

  errors:
    missing_return: error
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    constant_identifier_names: ignore
    no_logic_in_create_state: ignore

    #Ignoring for now, but prints should be refactor to Logging, and remove it here afterwards
    avoid_print: ignore

    #Following this rule would make us refactor the app_strings.dart, so it is a no for now
    prefer_const_literals_to_create_immutables: ignore

dart_code_metrics:
  # anti-patterns:
    # - long-method
  metrics:
    maximum-nesting-level: 5
    source-lines-of-code: 60
  metrics-exclude:
    - test/**
  rules:
    - binary-expression-operand-order
    - no-boolean-literal-compare
    - no-equal-then-else
    - always-remove-listener
    - avoid-unused-parameters